version: '3'
services:
  client:
    image: "mphbo777/music-corner-client"
    mem_limit: 128m
    hostname: client
  server:
    image: mphbo777/music-corner-server
    mem_limit: 128m
    hostname: api
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    image: "mphbo777/music-corner-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'