version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  client:
    depends_on:
      - postgres 
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    build:
      dockerfile: Dockerfile.dev
      context: './client'
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    