import { Box, Grid } from "grommet";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { SoundCloudWidget } from "../components/SoundCloudWidget";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const users = [
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
    {
      url: "https://soundcloud.com/rwdy-music/get-rwdy-3",
      username: "Gregolas",
    },
  ];
  const players = users.map((user) => <SoundCloudWidget {...user} />);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>ShwackCloud</h3>
        <h2>Your music... just shwacked.</h2>
        <Grid columns={["medium"]}>{players}</Grid>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
