import { Box, Button, Form, FormField, TextInput } from "grommet";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Registration.module.scss";

interface IFormData {
  email: string;
  password: string;
}

const initialState = {
  email: "",
  password: "",
};

const Login: NextPage = () => {
  const [formData, setFormData] = useState<IFormData>(initialState);

  const handleSubmit = (value: IFormData) => {};

  const handleReset = () => {
    setFormData(initialState);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.register}>Login</h1>
        <Form
          className={styles.form}
          value={formData}
          onChange={(value) => setFormData(value)}
          onReset={handleReset}
          onSubmit={({ value }) => handleSubmit(value)}
        >
          <FormField name="email" label="Email">
            <TextInput name="email" />
          </FormField>
          <FormField name="password" label="Password">
            <TextInput name="password" />
          </FormField>
          <Box className={styles.buttonGroup} direction="row" gap="medium">
            <Button type="submit" primary label="Submit" />
            <Button type="reset" secondary label="Reset" />
          </Box>
        </Form>
        <Link href="/registration">
          <p className={styles.account}>Don't have an account? Register</p>
        </Link>
      </main>
    </div>
  );
};

export default Login;
