import { Anchor, Box, Form, Grid } from "grommet";
import { Play } from "grommet-icons";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

const Registration: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Registration;
